// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

/**
 * Attachment 附件信息（站点/书签共用）
 */
export class Attachment {
    "filename": string;
    "label"?: string;

    /** Creates a new Attachment instance. */
    constructor($$source: Partial<Attachment> = {}) {
        if (!("filename" in $$source)) {
            this["filename"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Attachment instance from a string or object.
     */
    static createFrom($$source: any = {}): Attachment {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Attachment($$parsedSource as Partial<Attachment>);
    }
}

/**
 * Bookmark 书签实体
 */
export class Bookmark {
    "id": string;
    "url": string;
    "domain": string;
    "site_id": string;
    "title": string;
    "cover"?: string;
    "description"?: string;
    "tags": string[];
    "attachments": Attachment[];
    "status": string;
    "created_at": time$0.Time;
    "updated_at": time$0.Time;

    /** Creates a new Bookmark instance. */
    constructor($$source: Partial<Bookmark> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("domain" in $$source)) {
            this["domain"] = "";
        }
        if (!("site_id" in $$source)) {
            this["site_id"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("tags" in $$source)) {
            this["tags"] = [];
        }
        if (!("attachments" in $$source)) {
            this["attachments"] = [];
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = null;
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Bookmark instance from a string or object.
     */
    static createFrom($$source: any = {}): Bookmark {
        const $$createField7_0 = $$createType0;
        const $$createField8_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField7_0($$parsedSource["tags"]);
        }
        if ("attachments" in $$parsedSource) {
            $$parsedSource["attachments"] = $$createField8_0($$parsedSource["attachments"]);
        }
        return new Bookmark($$parsedSource as Partial<Bookmark>);
    }
}

/**
 * BookmarkListReq 书签列表请求
 */
export class BookmarkListReq {
    "page": number;
    "page_size": number;
    "search"?: string;
    "tags"?: string[];
    "site_id"?: string;

    /** Creates a new BookmarkListReq instance. */
    constructor($$source: Partial<BookmarkListReq> = {}) {
        if (!("page" in $$source)) {
            this["page"] = 0;
        }
        if (!("page_size" in $$source)) {
            this["page_size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BookmarkListReq instance from a string or object.
     */
    static createFrom($$source: any = {}): BookmarkListReq {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField3_0($$parsedSource["tags"]);
        }
        return new BookmarkListReq($$parsedSource as Partial<BookmarkListReq>);
    }
}

/**
 * BookmarkListResult 书签列表响应
 */
export class BookmarkListResult {
    "items": Bookmark[];
    "total": number;
    "has_more": boolean;

    /** Creates a new BookmarkListResult instance. */
    constructor($$source: Partial<BookmarkListResult> = {}) {
        if (!("items" in $$source)) {
            this["items"] = [];
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("has_more" in $$source)) {
            this["has_more"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BookmarkListResult instance from a string or object.
     */
    static createFrom($$source: any = {}): BookmarkListResult {
        const $$createField0_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField0_0($$parsedSource["items"]);
        }
        return new BookmarkListResult($$parsedSource as Partial<BookmarkListResult>);
    }
}

/**
 * CreateBookmarkReq 创建书签请求
 */
export class CreateBookmarkReq {
    "url": string;
    "site_id": string;
    "title": string;
    "description"?: string;
    "tags"?: string[];

    /** Creates a new CreateBookmarkReq instance. */
    constructor($$source: Partial<CreateBookmarkReq> = {}) {
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("site_id" in $$source)) {
            this["site_id"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreateBookmarkReq instance from a string or object.
     */
    static createFrom($$source: any = {}): CreateBookmarkReq {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField4_0($$parsedSource["tags"]);
        }
        return new CreateBookmarkReq($$parsedSource as Partial<CreateBookmarkReq>);
    }
}

/**
 * CreateSiteReq 创建站点请求
 */
export class CreateSiteReq {
    "title": string;
    "domain": string;
    "description"?: string;
    "tags"?: string[];

    /** Creates a new CreateSiteReq instance. */
    constructor($$source: Partial<CreateSiteReq> = {}) {
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("domain" in $$source)) {
            this["domain"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreateSiteReq instance from a string or object.
     */
    static createFrom($$source: any = {}): CreateSiteReq {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField3_0($$parsedSource["tags"]);
        }
        return new CreateSiteReq($$parsedSource as Partial<CreateSiteReq>);
    }
}

/**
 * LookupSiteByURLReq 根据 URL 查询对应站点请求
 */
export class LookupSiteByURLReq {
    "url": string;

    /** Creates a new LookupSiteByURLReq instance. */
    constructor($$source: Partial<LookupSiteByURLReq> = {}) {
        if (!("url" in $$source)) {
            this["url"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LookupSiteByURLReq instance from a string or object.
     */
    static createFrom($$source: any = {}): LookupSiteByURLReq {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LookupSiteByURLReq($$parsedSource as Partial<LookupSiteByURLReq>);
    }
}

/**
 * LookupSiteResult 站点查询结果
 */
export class LookupSiteResult {
    "found": boolean;
    "site_id"?: string;
    "domain": string;

    /** Creates a new LookupSiteResult instance. */
    constructor($$source: Partial<LookupSiteResult> = {}) {
        if (!("found" in $$source)) {
            this["found"] = false;
        }
        if (!("domain" in $$source)) {
            this["domain"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LookupSiteResult instance from a string or object.
     */
    static createFrom($$source: any = {}): LookupSiteResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LookupSiteResult($$parsedSource as Partial<LookupSiteResult>);
    }
}

/**
 * QueueItem 临时队列条目（无对应站点时暂存 URL）
 */
export class QueueItem {
    "id": string;
    "url": string;
    "added_at": time$0.Time;

    /** Creates a new QueueItem instance. */
    constructor($$source: Partial<QueueItem> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("added_at" in $$source)) {
            this["added_at"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QueueItem instance from a string or object.
     */
    static createFrom($$source: any = {}): QueueItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new QueueItem($$parsedSource as Partial<QueueItem>);
    }
}

/**
 * Site 站点实体
 */
export class Site {
    "id": string;
    "title": string;
    "domain": string;
    "icon"?: string;
    "cover"?: string;
    "description"?: string;
    "tags": string[];
    "attachments": Attachment[];
    "bookmark_count": number;
    "created_at": time$0.Time;
    "updated_at": time$0.Time;

    /** Creates a new Site instance. */
    constructor($$source: Partial<Site> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("domain" in $$source)) {
            this["domain"] = "";
        }
        if (!("tags" in $$source)) {
            this["tags"] = [];
        }
        if (!("attachments" in $$source)) {
            this["attachments"] = [];
        }
        if (!("bookmark_count" in $$source)) {
            this["bookmark_count"] = 0;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = null;
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Site instance from a string or object.
     */
    static createFrom($$source: any = {}): Site {
        const $$createField6_0 = $$createType0;
        const $$createField7_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField6_0($$parsedSource["tags"]);
        }
        if ("attachments" in $$parsedSource) {
            $$parsedSource["attachments"] = $$createField7_0($$parsedSource["attachments"]);
        }
        return new Site($$parsedSource as Partial<Site>);
    }
}

/**
 * SiteListReq 站点列表请求
 */
export class SiteListReq {
    "page": number;
    "page_size": number;
    "search"?: string;
    "tags"?: string[];

    /** Creates a new SiteListReq instance. */
    constructor($$source: Partial<SiteListReq> = {}) {
        if (!("page" in $$source)) {
            this["page"] = 0;
        }
        if (!("page_size" in $$source)) {
            this["page_size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SiteListReq instance from a string or object.
     */
    static createFrom($$source: any = {}): SiteListReq {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField3_0($$parsedSource["tags"]);
        }
        return new SiteListReq($$parsedSource as Partial<SiteListReq>);
    }
}

/**
 * SiteListResult 站点列表响应
 */
export class SiteListResult {
    "items": Site[];
    "total": number;
    "has_more": boolean;

    /** Creates a new SiteListResult instance. */
    constructor($$source: Partial<SiteListResult> = {}) {
        if (!("items" in $$source)) {
            this["items"] = [];
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("has_more" in $$source)) {
            this["has_more"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SiteListResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SiteListResult {
        const $$createField0_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField0_0($$parsedSource["items"]);
        }
        return new SiteListResult($$parsedSource as Partial<SiteListResult>);
    }
}

/**
 * UpdateBookmarkReq 更新书签请求
 */
export class UpdateBookmarkReq {
    "id": string;
    "title"?: string | null;
    "description"?: string | null;
    "tags"?: string[] | null;
    "cover"?: string | null;
    "attachments"?: Attachment[] | null;

    /** Creates a new UpdateBookmarkReq instance. */
    constructor($$source: Partial<UpdateBookmarkReq> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateBookmarkReq instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateBookmarkReq {
        const $$createField3_0 = $$createType7;
        const $$createField5_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField3_0($$parsedSource["tags"]);
        }
        if ("attachments" in $$parsedSource) {
            $$parsedSource["attachments"] = $$createField5_0($$parsedSource["attachments"]);
        }
        return new UpdateBookmarkReq($$parsedSource as Partial<UpdateBookmarkReq>);
    }
}

/**
 * UpdateSiteReq 更新站点请求
 */
export class UpdateSiteReq {
    "id": string;
    "title"?: string | null;
    "description"?: string | null;
    "tags"?: string[] | null;
    "icon"?: string | null;
    "cover"?: string | null;
    "attachments"?: Attachment[] | null;

    /** Creates a new UpdateSiteReq instance. */
    constructor($$source: Partial<UpdateSiteReq> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateSiteReq instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateSiteReq {
        const $$createField3_0 = $$createType7;
        const $$createField6_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField3_0($$parsedSource["tags"]);
        }
        if ("attachments" in $$parsedSource) {
            $$parsedSource["attachments"] = $$createField6_0($$parsedSource["attachments"]);
        }
        return new UpdateSiteReq($$parsedSource as Partial<UpdateSiteReq>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = Attachment.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = Bookmark.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = Site.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = $Create.Nullable($$createType0);
const $$createType8 = $Create.Nullable($$createType2);
