// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * URLService 站点 + 书签 + 临时队列的业务逻辑层。
 * 公开方法即前端可调用接口（通过 Wails 绑定）。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

/**
 * AddToQueue 将 URL 加入临时队列
 */
export function AddToQueue(rawURL: string): $CancellablePromise<model$0.QueueItem | null> {
    return $Call.ByID(1752351547, rawURL).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * BatchDeleteBookmarks 批量删除书签。汇总所有被删除书签的标签后
 * 一次性更新 url_tag 注册表 count，并逐个清理文件资源。
 */
export function BatchDeleteBookmarks(ids: string[]): $CancellablePromise<void> {
    return $Call.ByID(2846298918, ids);
}

/**
 * BatchTagBookmarks 批量为书签追加标签（不覆盖已有标签），
 * 同步维护 url_tag 注册表 count。
 */
export function BatchTagBookmarks(ids: string[], tagsToAdd: string[]): $CancellablePromise<void> {
    return $Call.ByID(4245467, ids, tagsToAdd);
}

/**
 * ClearQueue 清空临时队列
 */
export function ClearQueue(): $CancellablePromise<void> {
    return $Call.ByID(2788114270);
}

/**
 * CreateBookmark 创建书签。校验 URL 合法性，自动提取域名匹配站点，
 * 归一化标签并维护 url_tag 注册表 count。
 * 若 SiteID 非空则直接使用；否则按域名自动查找站点，
 * 未找到站点则存入临时队列而非创建书签。
 */
export function CreateBookmark(req: model$0.CreateBookmarkReq): $CancellablePromise<model$0.Bookmark | null> {
    return $Call.ByID(1571522930, req).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * CreateSite 创建站点。校验 title 必填、domain 格式，
 * 归一化标签并维护 url_tag 注册表 count。
 */
export function CreateSite(req: model$0.CreateSiteReq): $CancellablePromise<model$0.Site | null> {
    return $Call.ByID(3517194625, req).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * DeleteBookmark 删除单条书签。同步清理封面和附件文件，
 * 并递减 url_tag 注册表 count。
 */
export function DeleteBookmark(id: string): $CancellablePromise<void> {
    return $Call.ByID(3973746605, id);
}

/**
 * DeleteQueueItem 删除临时队列中的指定条目
 */
export function DeleteQueueItem(id: string): $CancellablePromise<void> {
    return $Call.ByID(3920910339, id);
}

/**
 * DeleteSite 删除站点。同步清理 icon、封面、附件目录，
 * 并递减 url_tag 注册表 count。
 */
export function DeleteSite(id: string): $CancellablePromise<void> {
    return $Call.ByID(1448431898, id);
}

/**
 * GetBookmark 按 ID 查询书签详情
 */
export function GetBookmark(id: string): $CancellablePromise<model$0.Bookmark | null> {
    return $Call.ByID(555994290, id).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetSite 按 ID 查询站点详情
 */
export function GetSite(id: string): $CancellablePromise<model$0.Site | null> {
    return $Call.ByID(1892363713, id).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * ListBookmarks 分页查询书签列表
 */
export function ListBookmarks(req: model$0.BookmarkListReq): $CancellablePromise<model$0.BookmarkListResult | null> {
    return $Call.ByID(3397416867, req).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * ListQueue 获取临时队列中所有条目（按 added_at 降序）
 */
export function ListQueue(): $CancellablePromise<model$0.QueueItem[]> {
    return $Call.ByID(1155762709).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * ListSites 分页查询站点列表
 */
export function ListSites(req: model$0.SiteListReq): $CancellablePromise<model$0.SiteListResult | null> {
    return $Call.ByID(2560653478, req).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * LookupSiteByURL 根据 URL 查询对应站点。
 * 提取 URL 中的域名，查找是否有对应站点。
 */
export function LookupSiteByURL(req: model$0.LookupSiteByURLReq): $CancellablePromise<model$0.LookupSiteResult | null> {
    return $Call.ByID(2083698959, req).then(($result: any) => {
        return $$createType12($result);
    });
}

/**
 * UpdateBookmark 更新书签。当 Tags 字段变化时维护 url_tag 注册表 count。
 */
export function UpdateBookmark(req: model$0.UpdateBookmarkReq): $CancellablePromise<model$0.Bookmark | null> {
    return $Call.ByID(3562436739, req).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * UpdateSite 更新站点。当 Tags 字段变化时维护 url_tag 注册表 count。
 */
export function UpdateSite(req: model$0.UpdateSiteReq): $CancellablePromise<model$0.Site | null> {
    return $Call.ByID(2630650532, req).then(($result: any) => {
        return $$createType5($result);
    });
}

// Private type creation functions
const $$createType0 = model$0.QueueItem.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = model$0.Bookmark.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = model$0.Site.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = model$0.BookmarkListResult.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = $Create.Array($$createType0);
const $$createType9 = model$0.SiteListResult.createFrom;
const $$createType10 = $Create.Nullable($$createType9);
const $$createType11 = model$0.LookupSiteResult.createFrom;
const $$createType12 = $Create.Nullable($$createType11);
